// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiZZklpXxX7tH_tENXPw9d03RF5qbNvnk',
    appId: '1:643763211290:web:bfdd8f315f3bd82a5e95a3',
    messagingSenderId: '643763211290',
    projectId: 'autism-detection-b00ea',
    authDomain: 'autism-detection-b00ea.firebaseapp.com',
    storageBucket: 'autism-detection-b00ea.firebasestorage.app',
    measurementId: 'G-N3TYNZN2D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjMaMzDVhf7OQ2qREVjIptPJ7jaFot_U',
    appId: '1:643763211290:android:1a0444c6d27f35bc5e95a3',
    messagingSenderId: '643763211290',
    projectId: 'autism-detection-b00ea',
    storageBucket: 'autism-detection-b00ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaaxG3rauRR8PrbrwRr7ett9i7P11DegI',
    appId: '1:643763211290:ios:a3f18bdbf5f9029e5e95a3',
    messagingSenderId: '643763211290',
    projectId: 'autism-detection-b00ea',
    storageBucket: 'autism-detection-b00ea.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaaxG3rauRR8PrbrwRr7ett9i7P11DegI',
    appId: '1:643763211290:ios:a3f18bdbf5f9029e5e95a3',
    messagingSenderId: '643763211290',
    projectId: 'autism-detection-b00ea',
    storageBucket: 'autism-detection-b00ea.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiZZklpXxX7tH_tENXPw9d03RF5qbNvnk',
    appId: '1:643763211290:web:19005e1650f710425e95a3',
    messagingSenderId: '643763211290',
    projectId: 'autism-detection-b00ea',
    authDomain: 'autism-detection-b00ea.firebaseapp.com',
    storageBucket: 'autism-detection-b00ea.firebasestorage.app',
    measurementId: 'G-LLJJCCTF59',
  );
}
